## To predict whether they purchase or not based on their Age, Sex and Estiamted Salary by Social_Network_Ads.

## Naive Bayes Algorithms

In [1]:
#Library Files load
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Dataset Load
data=pd.read_csv("Social_Network_Ads.csv")

In [3]:
data.shape

(400, 5)

In [4]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
data=pd.get_dummies(data,drop_first=True)

In [6]:
data.head()

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   19            19000          0            1
1  15810944   35            20000          0            1
2  15668575   26            43000          0            0
3  15603246   27            57000          0            0
4  15804002   19            76000          0            1

In [7]:
data=data.drop("User ID",axis=1)

In [8]:
data.head()

Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [9]:
data["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [10]:
x=data[["Age","EstimatedSalary","Gender_Male"]]
y=data["Purchased"]

In [11]:
x.shape

(400, 3)

In [12]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [13]:
#Split into training set and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=1/3,random_state=0)

In [14]:
import warnings
warnings.filterwarnings('ignore')

### 1. Gaussian Naive Bayes

In [15]:
from sklearn.naive_bayes import GaussianNB
Classifier = GaussianNB()
Classifier.fit(x_train, y_train)

y_pred = Classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

print(clf_report)


[[80  5]
 [ 8 41]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



### 2. Multinomial Naive Bayes

In [16]:
from sklearn.naive_bayes import MultinomialNB
Classifier = MultinomialNB()
Classifier.fit(x_train, y_train)

y_pred = Classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

print(clf_report)

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



### 3. Bernoulli Naive Bayes

In [17]:
from sklearn.naive_bayes import BernoulliNB
Classifier = BernoulliNB()
Classifier.fit(x_train, y_train)

y_pred = Classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

print(clf_report)

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



### 4. Categorical Naive Bayes

In [18]:
from sklearn.naive_bayes import CategoricalNB
Classifier = CategoricalNB()
Classifier.fit(x_train, y_train)

y_pred = Classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

print(clf_report)

[[82  3]
 [18 31]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134



### 5. Complement Naive Bayes

In [19]:
from sklearn.naive_bayes import ComplementNB
Classifier = ComplementNB()
Classifier.fit(x_train, y_train)

y_pred = Classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

print(clf_report)

[[40 45]
 [20 29]]
              precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134

